// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: routing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lat            float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng            float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Demand         int32                  `protobuf:"varint,4,opt,name=demand,proto3" json:"demand,omitempty"`
	ServiceTime    int32                  `protobuf:"varint,5,opt,name=service_time,json=serviceTime,proto3" json:"service_time,omitempty"`
	TwStart        int32                  `protobuf:"varint,6,opt,name=tw_start,json=twStart,proto3" json:"tw_start,omitempty"` // minutes from midnight
	TwEnd          int32                  `protobuf:"varint,7,opt,name=tw_end,json=twEnd,proto3" json:"tw_end,omitempty"`       // minutes from midnight
	Tags           []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Type           string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`                                             // depot | delivery | pickup
	PairId         string                 `protobuf:"bytes,10,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`                          // links pickup↔delivery; empty if not a PD pair
	Priority       int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`                                   // 1=low 2=medium 3=high 4=critical 0=unset
	DeadlineMin    int32                  `protobuf:"varint,12,opt,name=deadline_min,json=deadlineMin,proto3" json:"deadline_min,omitempty"`          // minutes from planning midnight; 0=no deadline
	LinehaulDemand int32                  `protobuf:"varint,13,opt,name=linehaul_demand,json=linehaulDemand,proto3" json:"linehaul_demand,omitempty"` // delivery load consumed from depot; 0 = derive from demand/type
	BackhaulDemand int32                  `protobuf:"varint,14,opt,name=backhaul_demand,json=backhaulDemand,proto3" json:"backhaul_demand,omitempty"` // pickup load added on route; 0 = derive from demand/type
	MustServe      bool                   `protobuf:"varint,15,opt,name=must_serve,json=mustServe,proto3" json:"must_serve,omitempty"`                // true = should not be dropped unless infeasible
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Node) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Node) GetDemand() int32 {
	if x != nil {
		return x.Demand
	}
	return 0
}

func (x *Node) GetServiceTime() int32 {
	if x != nil {
		return x.ServiceTime
	}
	return 0
}

func (x *Node) GetTwStart() int32 {
	if x != nil {
		return x.TwStart
	}
	return 0
}

func (x *Node) GetTwEnd() int32 {
	if x != nil {
		return x.TwEnd
	}
	return 0
}

func (x *Node) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetPairId() string {
	if x != nil {
		return x.PairId
	}
	return ""
}

func (x *Node) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Node) GetDeadlineMin() int32 {
	if x != nil {
		return x.DeadlineMin
	}
	return 0
}

func (x *Node) GetLinehaulDemand() int32 {
	if x != nil {
		return x.LinehaulDemand
	}
	return 0
}

func (x *Node) GetBackhaulDemand() int32 {
	if x != nil {
		return x.BackhaulDemand
	}
	return 0
}

func (x *Node) GetMustServe() bool {
	if x != nil {
		return x.MustServe
	}
	return false
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	ShiftStart    int32                  `protobuf:"varint,3,opt,name=shift_start,json=shiftStart,proto3" json:"shift_start,omitempty"` // minutes from midnight
	ShiftEnd      int32                  `protobuf:"varint,4,opt,name=shift_end,json=shiftEnd,proto3" json:"shift_end,omitempty"`       // minutes from midnight
	BreakStart    int32                  `protobuf:"varint,5,opt,name=break_start,json=breakStart,proto3" json:"break_start,omitempty"` // 0 = no break
	BreakEnd      int32                  `protobuf:"varint,6,opt,name=break_end,json=breakEnd,proto3" json:"break_end,omitempty"`
	MaxTasks      int32                  `protobuf:"varint,7,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`           // 0 = unlimited
	MaxDistance   float64                `protobuf:"fixed64,8,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"` // meters; 0 = unlimited
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	FixedCost     float64                `protobuf:"fixed64,10,opt,name=fixed_cost,json=fixedCost,proto3" json:"fixed_cost,omitempty"`
	CostPerKm     float64                `protobuf:"fixed64,11,opt,name=cost_per_km,json=costPerKm,proto3" json:"cost_per_km,omitempty"`
	Type          string                 `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{1}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Vehicle) GetShiftStart() int32 {
	if x != nil {
		return x.ShiftStart
	}
	return 0
}

func (x *Vehicle) GetShiftEnd() int32 {
	if x != nil {
		return x.ShiftEnd
	}
	return 0
}

func (x *Vehicle) GetBreakStart() int32 {
	if x != nil {
		return x.BreakStart
	}
	return 0
}

func (x *Vehicle) GetBreakEnd() int32 {
	if x != nil {
		return x.BreakEnd
	}
	return 0
}

func (x *Vehicle) GetMaxTasks() int32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

func (x *Vehicle) GetMaxDistance() float64 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

func (x *Vehicle) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Vehicle) GetFixedCost() float64 {
	if x != nil {
		return x.FixedCost
	}
	return 0
}

func (x *Vehicle) GetCostPerKm() float64 {
	if x != nil {
		return x.CostPerKm
	}
	return 0
}

func (x *Vehicle) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SolveRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Depot             *Node                  `protobuf:"bytes,1,opt,name=depot,proto3" json:"depot,omitempty"`
	Nodes             []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Vehicles          []*Vehicle             `protobuf:"bytes,3,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	Durations         []float64              `protobuf:"fixed64,4,rep,packed,name=durations,proto3" json:"durations,omitempty"`             // flattened n×n, row-major (minutes)
	Distances         []float64              `protobuf:"fixed64,5,rep,packed,name=distances,proto3" json:"distances,omitempty"`             // flattened n×n, row-major (meters)
	MatrixSize        int32                  `protobuf:"varint,6,opt,name=matrix_size,json=matrixSize,proto3" json:"matrix_size,omitempty"` // n (depot + nodes)
	TimeLimitMs       int32                  `protobuf:"varint,7,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	EnableAlns        bool                   `protobuf:"varint,8,opt,name=enable_alns,json=enableAlns,proto3" json:"enable_alns,omitempty"`
	EnableMultiTrip   bool                   `protobuf:"varint,9,opt,name=enable_multi_trip,json=enableMultiTrip,proto3" json:"enable_multi_trip,omitempty"`
	ReloadMin         int32                  `protobuf:"varint,10,opt,name=reload_min,json=reloadMin,proto3" json:"reload_min,omitempty"`                     // minutes; 0 = use server default (30)
	Seed              uint32                 `protobuf:"varint,11,opt,name=seed,proto3" json:"seed,omitempty"`                                                // 0 = non-deterministic
	MultiStartCount   int32                  `protobuf:"varint,12,opt,name=multi_start_count,json=multiStartCount,proto3" json:"multi_start_count,omitempty"` // 0 = use server default (2)
	DisableCapacity   bool                   `protobuf:"varint,13,opt,name=disable_capacity,json=disableCapacity,proto3" json:"disable_capacity,omitempty"`
	DisableTimeWindow bool                   `protobuf:"varint,14,opt,name=disable_time_window,json=disableTimeWindow,proto3" json:"disable_time_window,omitempty"`
	WeightDistance    float64                `protobuf:"fixed64,15,opt,name=weight_distance,json=weightDistance,proto3" json:"weight_distance,omitempty"` // objective weight on distance; both weights 0 = server default (0.5/0.5)
	WeightCost        float64                `protobuf:"fixed64,16,opt,name=weight_cost,json=weightCost,proto3" json:"weight_cost,omitempty"`             // objective weight on cost
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SolveRequest) Reset() {
	*x = SolveRequest{}
	mi := &file_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveRequest) ProtoMessage() {}

func (x *SolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveRequest.ProtoReflect.Descriptor instead.
func (*SolveRequest) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{2}
}

func (x *SolveRequest) GetDepot() *Node {
	if x != nil {
		return x.Depot
	}
	return nil
}

func (x *SolveRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SolveRequest) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *SolveRequest) GetDurations() []float64 {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *SolveRequest) GetDistances() []float64 {
	if x != nil {
		return x.Distances
	}
	return nil
}

func (x *SolveRequest) GetMatrixSize() int32 {
	if x != nil {
		return x.MatrixSize
	}
	return 0
}

func (x *SolveRequest) GetTimeLimitMs() int32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *SolveRequest) GetEnableAlns() bool {
	if x != nil {
		return x.EnableAlns
	}
	return false
}

func (x *SolveRequest) GetEnableMultiTrip() bool {
	if x != nil {
		return x.EnableMultiTrip
	}
	return false
}

func (x *SolveRequest) GetReloadMin() int32 {
	if x != nil {
		return x.ReloadMin
	}
	return 0
}

func (x *SolveRequest) GetSeed() uint32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *SolveRequest) GetMultiStartCount() int32 {
	if x != nil {
		return x.MultiStartCount
	}
	return 0
}

func (x *SolveRequest) GetDisableCapacity() bool {
	if x != nil {
		return x.DisableCapacity
	}
	return false
}

func (x *SolveRequest) GetDisableTimeWindow() bool {
	if x != nil {
		return x.DisableTimeWindow
	}
	return false
}

func (x *SolveRequest) GetWeightDistance() float64 {
	if x != nil {
		return x.WeightDistance
	}
	return 0
}

func (x *SolveRequest) GetWeightCost() float64 {
	if x != nil {
		return x.WeightCost
	}
	return 0
}

type DropReason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropReason) Reset() {
	*x = DropReason{}
	mi := &file_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropReason) ProtoMessage() {}

func (x *DropReason) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropReason.ProtoReflect.Descriptor instead.
func (*DropReason) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{3}
}

func (x *DropReason) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DropReason) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DropReason) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type RouteStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ArrivalMin    int32                  `protobuf:"varint,2,opt,name=arrival_min,json=arrivalMin,proto3" json:"arrival_min,omitempty"` // minutes from midnight
	DepartMin     int32                  `protobuf:"varint,3,opt,name=depart_min,json=departMin,proto3" json:"depart_min,omitempty"`    // minutes from midnight
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteStop) Reset() {
	*x = RouteStop{}
	mi := &file_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStop) ProtoMessage() {}

func (x *RouteStop) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStop.ProtoReflect.Descriptor instead.
func (*RouteStop) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{4}
}

func (x *RouteStop) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteStop) GetArrivalMin() int32 {
	if x != nil {
		return x.ArrivalMin
	}
	return 0
}

func (x *RouteStop) GetDepartMin() int32 {
	if x != nil {
		return x.DepartMin
	}
	return 0
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Stops         []*RouteStop           `protobuf:"bytes,2,rep,name=stops,proto3" json:"stops,omitempty"`
	TotalDistance float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"` // meters
	TotalDuration int32                  `protobuf:"varint,4,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`  // minutes
	TripSizes     []int32                `protobuf:"varint,5,rep,packed,name=trip_sizes,json=tripSizes,proto3" json:"trip_sizes,omitempty"`       // number of stops per trip (multi-trip vehicles)
	TotalCost     float64                `protobuf:"fixed64,6,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{5}
}

func (x *Route) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Route) GetStops() []*RouteStop {
	if x != nil {
		return x.Stops
	}
	return nil
}

func (x *Route) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *Route) GetTotalDuration() int32 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

func (x *Route) GetTripSizes() []int32 {
	if x != nil {
		return x.TripSizes
	}
	return nil
}

func (x *Route) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type SolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Unassigned    []string               `protobuf:"bytes,2,rep,name=unassigned,proto3" json:"unassigned,omitempty"`
	Objective     float64                `protobuf:"fixed64,3,opt,name=objective,proto3" json:"objective,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // OK | INFEASIBLE | TIMEOUT
	DropReasons   []*DropReason          `protobuf:"bytes,5,rep,name=drop_reasons,json=dropReasons,proto3" json:"drop_reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveResponse) Reset() {
	*x = SolveResponse{}
	mi := &file_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveResponse) ProtoMessage() {}

func (x *SolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveResponse.ProtoReflect.Descriptor instead.
func (*SolveResponse) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{6}
}

func (x *SolveResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *SolveResponse) GetUnassigned() []string {
	if x != nil {
		return x.Unassigned
	}
	return nil
}

func (x *SolveResponse) GetObjective() float64 {
	if x != nil {
		return x.Objective
	}
	return 0
}

func (x *SolveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SolveResponse) GetDropReasons() []*DropReason {
	if x != nil {
		return x.DropReasons
	}
	return nil
}

var File_routing_proto protoreflect.FileDescriptor

const file_routing_proto_rawDesc = "" +
	"\n" +
	"\rrouting.proto\x12\x06solver\"\x98\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\x12\x16\n" +
	"\x06demand\x18\x04 \x01(\x05R\x06demand\x12!\n" +
	"\fservice_time\x18\x05 \x01(\x05R\vserviceTime\x12\x19\n" +
	"\btw_start\x18\x06 \x01(\x05R\atwStart\x12\x15\n" +
	"\x06tw_end\x18\a \x01(\x05R\x05twEnd\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12\x17\n" +
	"\apair_id\x18\n" +
	" \x01(\tR\x06pairId\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12!\n" +
	"\fdeadline_min\x18\f \x01(\x05R\vdeadlineMin\x12'\n" +
	"\x0flinehaul_demand\x18\r \x01(\x05R\x0elinehaulDemand\x12'\n" +
	"\x0fbackhaul_demand\x18\x0e \x01(\x05R\x0ebackhaulDemand\x12\x1d\n" +
	"\n" +
	"must_serve\x18\x0f \x01(\bR\tmustServe\"\xd8\x02\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vshift_start\x18\x03 \x01(\x05R\n" +
	"shiftStart\x12\x1b\n" +
	"\tshift_end\x18\x04 \x01(\x05R\bshiftEnd\x12\x1f\n" +
	"\vbreak_start\x18\x05 \x01(\x05R\n" +
	"breakStart\x12\x1b\n" +
	"\tbreak_end\x18\x06 \x01(\x05R\bbreakEnd\x12\x1b\n" +
	"\tmax_tasks\x18\a \x01(\x05R\bmaxTasks\x12!\n" +
	"\fmax_distance\x18\b \x01(\x01R\vmaxDistance\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"fixed_cost\x18\n" +
	" \x01(\x01R\tfixedCost\x12\x1e\n" +
	"\vcost_per_km\x18\v \x01(\x01R\tcostPerKm\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\"\xd5\x04\n" +
	"\fSolveRequest\x12\"\n" +
	"\x05depot\x18\x01 \x01(\v2\f.solver.NodeR\x05depot\x12\"\n" +
	"\x05nodes\x18\x02 \x03(\v2\f.solver.NodeR\x05nodes\x12+\n" +
	"\bvehicles\x18\x03 \x03(\v2\x0f.solver.VehicleR\bvehicles\x12\x1c\n" +
	"\tdurations\x18\x04 \x03(\x01R\tdurations\x12\x1c\n" +
	"\tdistances\x18\x05 \x03(\x01R\tdistances\x12\x1f\n" +
	"\vmatrix_size\x18\x06 \x01(\x05R\n" +
	"matrixSize\x12\"\n" +
	"\rtime_limit_ms\x18\a \x01(\x05R\vtimeLimitMs\x12\x1f\n" +
	"\venable_alns\x18\b \x01(\bR\n" +
	"enableAlns\x12*\n" +
	"\x11enable_multi_trip\x18\t \x01(\bR\x0fenableMultiTrip\x12\x1d\n" +
	"\n" +
	"reload_min\x18\n" +
	" \x01(\x05R\treloadMin\x12\x12\n" +
	"\x04seed\x18\v \x01(\rR\x04seed\x12*\n" +
	"\x11multi_start_count\x18\f \x01(\x05R\x0fmultiStartCount\x12)\n" +
	"\x10disable_capacity\x18\r \x01(\bR\x0fdisableCapacity\x12.\n" +
	"\x13disable_time_window\x18\x0e \x01(\bR\x11disableTimeWindow\x12'\n" +
	"\x0fweight_distance\x18\x0f \x01(\x01R\x0eweightDistance\x12\x1f\n" +
	"\vweight_cost\x18\x10 \x01(\x01R\n" +
	"weightCost\"Q\n" +
	"\n" +
	"DropReason\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"d\n" +
	"\tRouteStop\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\varrival_min\x18\x02 \x01(\x05R\n" +
	"arrivalMin\x12\x1d\n" +
	"\n" +
	"depart_min\x18\x03 \x01(\x05R\tdepartMin\"\xdb\x01\n" +
	"\x05Route\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12'\n" +
	"\x05stops\x18\x02 \x03(\v2\x11.solver.RouteStopR\x05stops\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12%\n" +
	"\x0etotal_duration\x18\x04 \x01(\x05R\rtotalDuration\x12\x1d\n" +
	"\n" +
	"trip_sizes\x18\x05 \x03(\x05R\ttripSizes\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x06 \x01(\x01R\ttotalCost\"\xc3\x01\n" +
	"\rSolveResponse\x12%\n" +
	"\x06routes\x18\x01 \x03(\v2\r.solver.RouteR\x06routes\x12\x1e\n" +
	"\n" +
	"unassigned\x18\x02 \x03(\tR\n" +
	"unassigned\x12\x1c\n" +
	"\tobjective\x18\x03 \x01(\x01R\tobjective\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x125\n" +
	"\fdrop_reasons\x18\x05 \x03(\v2\x12.solver.DropReasonR\vdropReasons2E\n" +
	"\rSolverService\x124\n" +
	"\x05Solve\x12\x14.solver.SolveRequest\x1a\x15.solver.SolveResponseB2Z0github.com/ROP-TEAM/rop-algorithm/solver/grpc/pbb\x06proto3"

var (
	file_routing_proto_rawDescOnce sync.Once
	file_routing_proto_rawDescData []byte
)

func file_routing_proto_rawDescGZIP() []byte {
	file_routing_proto_rawDescOnce.Do(func() {
		file_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)))
	})
	return file_routing_proto_rawDescData
}

var file_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_routing_proto_goTypes = []any{
	(*Node)(nil),          // 0: solver.Node
	(*Vehicle)(nil),       // 1: solver.Vehicle
	(*SolveRequest)(nil),  // 2: solver.SolveRequest
	(*DropReason)(nil),    // 3: solver.DropReason
	(*RouteStop)(nil),     // 4: solver.RouteStop
	(*Route)(nil),         // 5: solver.Route
	(*SolveResponse)(nil), // 6: solver.SolveResponse
}
var file_routing_proto_depIdxs = []int32{
	0, // 0: solver.SolveRequest.depot:type_name -> solver.Node
	0, // 1: solver.SolveRequest.nodes:type_name -> solver.Node
	1, // 2: solver.SolveRequest.vehicles:type_name -> solver.Vehicle
	4, // 3: solver.Route.stops:type_name -> solver.RouteStop
	5, // 4: solver.SolveResponse.routes:type_name -> solver.Route
	3, // 5: solver.SolveResponse.drop_reasons:type_name -> solver.DropReason
	2, // 6: solver.SolverService.Solve:input_type -> solver.SolveRequest
	6, // 7: solver.SolverService.Solve:output_type -> solver.SolveResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_routing_proto_init() }
func file_routing_proto_init() {
	if File_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routing_proto_goTypes,
		DependencyIndexes: file_routing_proto_depIdxs,
		MessageInfos:      file_routing_proto_msgTypes,
	}.Build()
	File_routing_proto = out.File
	file_routing_proto_goTypes = nil
	file_routing_proto_depIdxs = nil
}
