// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: solver.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SolverService_Solve_FullMethodName = "/solver.SolverService/Solve"
)

// SolverServiceClient is the client API for SolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolverServiceClient interface {
	Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error)
}

type solverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolverServiceClient(cc grpc.ClientConnInterface) SolverServiceClient {
	return &solverServiceClient{cc}
}

func (c *solverServiceClient) Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveResponse)
	err := c.cc.Invoke(ctx, SolverService_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolverServiceServer is the server API for SolverService service.
// All implementations must embed UnimplementedSolverServiceServer
// for forward compatibility.
type SolverServiceServer interface {
	Solve(context.Context, *SolveRequest) (*SolveResponse, error)
	mustEmbedUnimplementedSolverServiceServer()
}

// UnimplementedSolverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolverServiceServer struct{}

func (UnimplementedSolverServiceServer) Solve(context.Context, *SolveRequest) (*SolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedSolverServiceServer) mustEmbedUnimplementedSolverServiceServer() {}
func (UnimplementedSolverServiceServer) testEmbeddedByValue()                       {}

// UnsafeSolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolverServiceServer will
// result in compilation errors.
type UnsafeSolverServiceServer interface {
	mustEmbedUnimplementedSolverServiceServer()
}

func RegisterSolverServiceServer(s grpc.ServiceRegistrar, srv SolverServiceServer) {
	// If the following call panics, it indicates UnimplementedSolverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SolverService_ServiceDesc, srv)
}

func _SolverService_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServiceServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolverService_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServiceServer).Solve(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolverService_ServiceDesc is the grpc.ServiceDesc for SolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solver.SolverService",
	HandlerType: (*SolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _SolverService_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solver.proto",
}
